FROM python:3.13-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

COPY requirements.txt .
RUN uv pip install --system --no-cache -r requirements.txt

# Копируем код бэкенда в подпапку /app/backend
COPY backend/ /app/backend/

# Создаём непривилегированного пользователя
RUN useradd --create-home appuser

# Создаём директорию для загрузок и даём права пользователю
RUN mkdir -p /app/backend/app/static/uploads && \
    chown -R appuser:appuser /app/backend/app/static/uploads

USER appuser

# Переходим в папку с кодом
WORKDIR /app/backend

# Запускаем video_check_worker
CMD ["python", "video_check_worker.py"]
