FROM python:3.13-slim

WORKDIR /app

COPY requirements_a.txt .
RUN pip install --no-cache-dir -r requirements_a.txt

# Копируем код webrtc в подпапку /app/webrtc
COPY webrtc/ /app/webrtc/

RUN pip install --no-cache-dir gunicorn==23.0.0 uvicorn websockets fastapi python-socketio httpx asyncpg aiosqlite

RUN useradd --create-home appuser
USER appuser

WORKDIR /app

EXPOSE 5000

# Продовый запуск асинхронного ASGI приложения через gunicorn + uvicorn worker
CMD ["python", "-m", "gunicorn", "-k", "uvicorn.workers.UvicornWorker", "-w", "1", "-b", "0.0.0.0:5000", "webrtc.main:asgi_app"]
