FROM python:3.13-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

COPY requirements.txt .
RUN uv pip install --system --no-cache -r requirements.txt

# Copy WebRTC code
COPY webrtc/ /app/webrtc/

RUN useradd --create-home appuser
USER appuser

WORKDIR /app

EXPOSE 5000

# Продовый запуск асинхронного ASGI приложения через gunicorn + uvicorn worker
CMD ["python", "-m", "gunicorn", "-k", "uvicorn.workers.UvicornWorker", "-w", "1", "-b", "0.0.0.0:5000", "webrtc.main:asgi_app"]
